### ISSUE TITLE
在未安装AE2的情况下右键蓝图引发崩溃

### ISSUE THREAD

**Issue by Sam-0324** [KasumiNova/ModularMachinery-Community-Edition#36]
如题，安装AE后右键蓝图不再引发崩溃，但蓝图未显示材料需求。
版本：1.11.1-r43

> Time: 8/4/23 4:24 PM
Description: Unexpected error
java.lang.NoClassDefFoundError: github/kasuminova/mmce/common/tile/MEItemOutputBus
	at hellfirepvp.modularmachinery.common.CommonProxy$GuiType.<clinit>(CommonProxy.java:224)
	at hellfirepvp.modularmachinery.common.item.ItemBlueprint.func_180614_a(ItemBlueprint.java:100)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: github.kasuminova.mmce.common.tile.MEItemOutputBus
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: github/kasuminova/mmce/common/tile/base/MEItemBus
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 20 more
Caused by: java.lang.ClassNotFoundException: github.kasuminova.mmce.common.tile.base.MEItemBus
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more

**Comment by KasumiNova** [comment]
单人模式还是多人模式？

**Comment by Sam-0324** [comment]
单人模式（未安装JEI）
&nbsp;



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月4日(星期五) 晚上6:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KasumiNova/ModularMachinery-Community-Edition] 在未安装AE2的情况下右键蓝图引发崩溃 (Issue #36)





 
单人模式还是多人模式？
